### PR TITLE
Fix generation closes #80

### LINKED ISSUE #80: [Bug]: Power ore doesn't generate?
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.1.3

### Minecraft version

1.20.1

### Mod version

4.1.0

### Java version

17

### Issue Description

I can't find power ore, it doesn't generate anywhere

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by allanf181**
Fix #80

### CODE REVIEW

**Comment by Mrbysco** [comment]
Looks good to me

**Comment by Mrbysco** [comment]
Please separate other additions in the future as a fix for the worldgen shouldn't randomly add item tags

**Comment by allanf181** [comment]
These tags are standard and without them compatibility with other mods would be broken.

**Comment by Mrbysco** [comment]
But it had no relation to fixing worldgen 🤷

**Pull request merged**
